#!/usr/bin/env python3

import shutil
import psutil

def check_disk_usage(disk):
    du = shutil.disk_usage(disk)
    free = du.free / du.total * 100
    return free > 20 #True if this much space free

def check_cpu_usage():
    usage = psutil.cpu_percent(1) #param in seconds
    return usage < 75 #True if cpu_usage below this

if not check_disk_usage('/') or not check_cpu_usage():
    print('ERROR!')
else:
    print('Everything is OK')
